package com.atom.apt.proxy

import com.atom.compiler.ksp.aap.`data`.AbstractStudent
import com.atom.compiler.ksp.aap.`data`.ManStudent
import com.atom.compiler.ksp.aap.`data`.Person
import com.atom.compiler.ksp.aap.`data`.Teacher
import com.atom.module.`annotation`.aap.AapAutoClass
import com.atom.module.`annotation`.aap.AapImplEntry
import java.lang.SuppressWarnings

/**
 * <p>This is a class automatically generated by API annotation processor.</p>
 * @date 2022-06-06T23:04:44.590+0800
 */
@AapAutoClass(
  value = ["AapSymbolProcessor"],
  data = "2022-06-06T23:04:44.590+0800"
)
@SuppressWarnings(value = ["all"])
public class App : AapImplEntry {
  public constructor() {
    add( "AbstractStudent" , Person::class.java , AbstractStudent::class.java , 1)
    add( "ManStudent" , Person::class.java , ManStudent::class.java , 3)
    add( "Teacher" , Person::class.java , Teacher::class.java , 2)
  }
}
