package com.atom.test

import com.atom.module.`annotation`.aap.AapAutoClass
import com.atom.module.`annotation`.aap.AapImplEntry
import java.lang.SuppressWarnings
import kotlin.String
import kotlin.Unit

/**
 * <p>This is a class automatically generated by API annotation processor.</p>
 * @date 2022-06-05T11:01:32.551+0800
 */
@AapAutoClass(
  value = ["2022-06-05T11:01:32.551+0800"],
  data = "2022-06-05T11:01:32.551+0800"
)
@SuppressWarnings(value = ["all"])
public class aap(
  public val name: String
) : AapImplEntry() {
  public fun greet(): Unit {
    println("""Hello, $name""")
  }
}

public fun main(vararg args: String): Unit {
  aap(args[0]).greet()
}
